//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehanizam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OzakonjenjaDirektorijum {
            get {
                return ((string)(this["OzakonjenjaDirektorijum"]));
            }
            set {
                this["OzakonjenjaDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KataloziDirektorijum {
            get {
                return ((string)(this["KataloziDirektorijum"]));
            }
            set {
                this["KataloziDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjektiDirektorijum {
            get {
                return ((string)(this["ProjektiDirektorijum"]));
            }
            set {
                this["ProjektiDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RevizijaDirektorijum {
            get {
                return ((string)(this["RevizijaDirektorijum"]));
            }
            set {
                this["RevizijaDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TehnickiPregledDirektorijum {
            get {
                return ((string)(this["TehnickiPregledDirektorijum"]));
            }
            set {
                this["TehnickiPregledDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PredmerPredracunDirektorijum {
            get {
                return ((string)(this["PredmerPredracunDirektorijum"]));
            }
            set {
                this["PredmerPredracunDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpecifikacijeMaterijalaDirektorijum {
            get {
                return ((string)(this["SpecifikacijeMaterijalaDirektorijum"]));
            }
            set {
                this["SpecifikacijeMaterijalaDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InformacijeBaza {
            get {
                return ((string)(this["InformacijeBaza"]));
            }
            set {
                this["InformacijeBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DelovodnikBaza {
            get {
                return ((string)(this["DelovodnikBaza"]));
            }
            set {
                this["DelovodnikBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PredracuniBaza {
            get {
                return ((string)(this["PredracuniBaza"]));
            }
            set {
                this["PredracuniBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacuniBaza {
            get {
                return ((string)(this["RacuniBaza"]));
            }
            set {
                this["RacuniBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PriznaniceBaza {
            get {
                return ((string)(this["PriznaniceBaza"]));
            }
            set {
                this["PriznaniceBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UplatniceBaza {
            get {
                return ((string)(this["UplatniceBaza"]));
            }
            set {
                this["UplatniceBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CeopBaza {
            get {
                return ((string)(this["CeopBaza"]));
            }
            set {
                this["CeopBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OvlascenjaBaza {
            get {
                return ((string)(this["OvlascenjaBaza"]));
            }
            set {
                this["OvlascenjaBaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PredracunPilot {
            get {
                return ((string)(this["PredracunPilot"]));
            }
            set {
                this["PredracunPilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunPilot {
            get {
                return ((string)(this["RacunPilot"]));
            }
            set {
                this["RacunPilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PriznanicaPilot {
            get {
                return ((string)(this["PriznanicaPilot"]));
            }
            set {
                this["PriznanicaPilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UplatnicaPilot {
            get {
                return ((string)(this["UplatnicaPilot"]));
            }
            set {
                this["UplatnicaPilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OvlascenjePilot {
            get {
                return ((string)(this["OvlascenjePilot"]));
            }
            set {
                this["OvlascenjePilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InformacijePristupBazi {
            get {
                return ((bool)(this["InformacijePristupBazi"]));
            }
            set {
                this["InformacijePristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DelovodnikPristupBazi {
            get {
                return ((bool)(this["DelovodnikPristupBazi"]));
            }
            set {
                this["DelovodnikPristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PredracuniPristupBazi {
            get {
                return ((bool)(this["PredracuniPristupBazi"]));
            }
            set {
                this["PredracuniPristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RacuniPristupBazi {
            get {
                return ((bool)(this["RacuniPristupBazi"]));
            }
            set {
                this["RacuniPristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PriznanicePristupBazi {
            get {
                return ((bool)(this["PriznanicePristupBazi"]));
            }
            set {
                this["PriznanicePristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UplatnicePristupBazi {
            get {
                return ((bool)(this["UplatnicePristupBazi"]));
            }
            set {
                this["UplatnicePristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CeopPristupBazi {
            get {
                return ((bool)(this["CeopPristupBazi"]));
            }
            set {
                this["CeopPristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OvlascenjaPristupBazi {
            get {
                return ((bool)(this["OvlascenjaPristupBazi"]));
            }
            set {
                this["OvlascenjaPristupBazi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OzakonjenjePristupDirektorijumu {
            get {
                return ((bool)(this["OzakonjenjePristupDirektorijumu"]));
            }
            set {
                this["OzakonjenjePristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OzakonjenjePredmetPristupDirektorijumu {
            get {
                return ((bool)(this["OzakonjenjePredmetPristupDirektorijumu"]));
            }
            set {
                this["OzakonjenjePredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KatalogPristupDirektorijumu {
            get {
                return ((bool)(this["KatalogPristupDirektorijumu"]));
            }
            set {
                this["KatalogPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KatalogPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["KatalogPredmetPristupDirektorijumu"]));
            }
            set {
                this["KatalogPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProjektiPristupDirektorijumu {
            get {
                return ((bool)(this["ProjektiPristupDirektorijumu"]));
            }
            set {
                this["ProjektiPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProjektiPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["ProjektiPredmetPristupDirektorijumu"]));
            }
            set {
                this["ProjektiPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RevizijaPristupDirektorijumu {
            get {
                return ((bool)(this["RevizijaPristupDirektorijumu"]));
            }
            set {
                this["RevizijaPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RevizijaPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["RevizijaPredmetPristupDirektorijumu"]));
            }
            set {
                this["RevizijaPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TehnickiPregledPristupDirektorijumu {
            get {
                return ((bool)(this["TehnickiPregledPristupDirektorijumu"]));
            }
            set {
                this["TehnickiPregledPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TehnickiPregledPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["TehnickiPregledPredmetPristupDirektorijumu"]));
            }
            set {
                this["TehnickiPregledPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PredmerPredracunPristupDirektorijumu {
            get {
                return ((bool)(this["PredmerPredracunPristupDirektorijumu"]));
            }
            set {
                this["PredmerPredracunPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PredmerPredracunPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["PredmerPredracunPredmetPristupDirektorijumu"]));
            }
            set {
                this["PredmerPredracunPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpecifikacijaMaterijalaPristupDirektorijumu {
            get {
                return ((bool)(this["SpecifikacijaMaterijalaPristupDirektorijumu"]));
            }
            set {
                this["SpecifikacijaMaterijalaPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpecifikacijaMaterijalaPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["SpecifikacijaMaterijalaPredmetPristupDirektorijumu"]));
            }
            set {
                this["SpecifikacijaMaterijalaPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LozinkaZaProgram {
            get {
                return ((string)(this["LozinkaZaProgram"]));
            }
            set {
                this["LozinkaZaProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LozinkaZaPodesavanja {
            get {
                return ((string)(this["LozinkaZaPodesavanja"]));
            }
            set {
                this["LozinkaZaPodesavanja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PismoPilot {
            get {
                return ((string)(this["PismoPilot"]));
            }
            set {
                this["PismoPilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EeeDirektorijum {
            get {
                return ((string)(this["EeeDirektorijum"]));
            }
            set {
                this["EeeDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EeePristupDirektorijumu {
            get {
                return ((bool)(this["EeePristupDirektorijumu"]));
            }
            set {
                this["EeePristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EeePredmetPristupDirektorijumu {
            get {
                return ((bool)(this["EeePredmetPristupDirektorijumu"]));
            }
            set {
                this["EeePredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PredracuniDirektorijum {
            get {
                return ((string)(this["PredracuniDirektorijum"]));
            }
            set {
                this["PredracuniDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PredracuniPristupDirektorijumu {
            get {
                return ((bool)(this["PredracuniPristupDirektorijumu"]));
            }
            set {
                this["PredracuniPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacuniDirektorijum {
            get {
                return ((string)(this["RacuniDirektorijum"]));
            }
            set {
                this["RacuniDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RacuniPristupDirektorijumu {
            get {
                return ((bool)(this["RacuniPristupDirektorijumu"]));
            }
            set {
                this["RacuniPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PriznaniceDirektorijum {
            get {
                return ((string)(this["PriznaniceDirektorijum"]));
            }
            set {
                this["PriznaniceDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PriznanicePristupDirektorijumu {
            get {
                return ((bool)(this["PriznanicePristupDirektorijumu"]));
            }
            set {
                this["PriznanicePristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UplatniceDirektorijum {
            get {
                return ((string)(this["UplatniceDirektorijum"]));
            }
            set {
                this["UplatniceDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UplatnicePristupDirektorijumu {
            get {
                return ((bool)(this["UplatnicePristupDirektorijumu"]));
            }
            set {
                this["UplatnicePristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OvlascenjaDirektorijum {
            get {
                return ((string)(this["OvlascenjaDirektorijum"]));
            }
            set {
                this["OvlascenjaDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OvlascenjaPristupDirektorijumu {
            get {
                return ((bool)(this["OvlascenjaPristupDirektorijumu"]));
            }
            set {
                this["OvlascenjaPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiLica {
            get {
                return ((string)(this["PotpisiPecatiLica"]));
            }
            set {
                this["PotpisiPecatiLica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiGP {
            get {
                return ((string)(this["PotpisiPecatiGP"]));
            }
            set {
                this["PotpisiPecatiGP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiA {
            get {
                return ((string)(this["PotpisiPecatiA"]));
            }
            set {
                this["PotpisiPecatiA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiK {
            get {
                return ((string)(this["PotpisiPecatiK"]));
            }
            set {
                this["PotpisiPecatiK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiH {
            get {
                return ((string)(this["PotpisiPecatiH"]));
            }
            set {
                this["PotpisiPecatiH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiE {
            get {
                return ((string)(this["PotpisiPecatiE"]));
            }
            set {
                this["PotpisiPecatiE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiTS {
            get {
                return ((string)(this["PotpisiPecatiTS"]));
            }
            set {
                this["PotpisiPecatiTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiM {
            get {
                return ((string)(this["PotpisiPecatiM"]));
            }
            set {
                this["PotpisiPecatiM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PotpisiPecatiEEE {
            get {
                return ((string)(this["PotpisiPecatiEEE"]));
            }
            set {
                this["PotpisiPecatiEEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaMesto {
            get {
                return ((string)(this["PvOvlascenjaMesto"]));
            }
            set {
                this["PvOvlascenjaMesto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaJedninaMnozina1 {
            get {
                return ((string)(this["PvOvlascenjaJedninaMnozina1"]));
            }
            set {
                this["PvOvlascenjaJedninaMnozina1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaOvlascenjeDao {
            get {
                return ((string)(this["PvOvlascenjaOvlascenjeDao"]));
            }
            set {
                this["PvOvlascenjaOvlascenjeDao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaOvlascenjePrimio {
            get {
                return ((string)(this["PvOvlascenjaOvlascenjePrimio"]));
            }
            set {
                this["PvOvlascenjaOvlascenjePrimio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaJedninaMnozina2 {
            get {
                return ((string)(this["PvOvlascenjaJedninaMnozina2"]));
            }
            set {
                this["PvOvlascenjaJedninaMnozina2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PvOvlascenjaKontekst {
            get {
                return ((string)(this["PvOvlascenjaKontekst"]));
            }
            set {
                this["PvOvlascenjaKontekst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CeopDirektorijum {
            get {
                return ((string)(this["CeopDirektorijum"]));
            }
            set {
                this["CeopDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CeopPristupDirektorijumu {
            get {
                return ((bool)(this["CeopPristupDirektorijumu"]));
            }
            set {
                this["CeopPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CeopPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["CeopPredmetPristupDirektorijumu"]));
            }
            set {
                this["CeopPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArhivaDirektorijum {
            get {
                return ((string)(this["ArhivaDirektorijum"]));
            }
            set {
                this["ArhivaDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArhivaKopijaDirektrijum {
            get {
                return ((string)(this["ArhivaKopijaDirektrijum"]));
            }
            set {
                this["ArhivaKopijaDirektrijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UgovoriDirektorijum {
            get {
                return ((string)(this["UgovoriDirektorijum"]));
            }
            set {
                this["UgovoriDirektorijum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UgovorPredmetPristupDirektorijumu {
            get {
                return ((bool)(this["UgovorPredmetPristupDirektorijumu"]));
            }
            set {
                this["UgovorPredmetPristupDirektorijumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UgovoriPristupDirektorijumu {
            get {
                return ((bool)(this["UgovoriPristupDirektorijumu"]));
            }
            set {
                this["UgovoriPristupDirektorijumu"] = value;
            }
        }
    }
}
